import type { EducatorCardProps } from "@/components/shared/educator-card";

/** Seeded demo roster — 28 educators across roles, tiers, and availability for stakeholder demos. */
export const MOCK_EDUCATORS: EducatorCardProps[] = [
    {
        id: "e_1",
        name: "Dr. Sarah Jenkins",
        headline: "Math Interventionist & Instructional Coach",
        avatarUrl: "https://randomuser.me/api/portraits/women/44.jpg",
        verificationTier: "premier",
        overallRating: 4.9,
        reviewCount: 42,
        gradeLevels: ["6_8", "9_12"],
        areasOfNeed: ["instruction_curriculum", "data"],
        engagementTypes: ["substitute", "consulting"],
        coverageRegions: ["region_1", "region_2"],
        startingRate: 75,
        availabilityStatus: "open",
        hasVideoIntro: true,
        badges: ["Background Checked", "State Licensed TX", "NBCT"],
    },
    {
        id: "e_2",
        name: "Marcus Cole, M.Ed",
        headline: "Behavioral Specialist & Special Ed Consultant",
        avatarUrl: "https://randomuser.me/api/portraits/men/32.jpg",
        verificationTier: "verified",
        overallRating: 4.7,
        reviewCount: 18,
        gradeLevels: ["k5", "6_8"],
        areasOfNeed: ["developmental_medical", "instruction_curriculum"],
        engagementTypes: ["permanent", "consulting"],
        coverageRegions: ["region_4"],
        startingRate: 85,
        availabilityStatus: "limited",
        hasVideoIntro: false,
        badges: ["Background Checked"],
    },
    {
        id: "e_3",
        name: "Elena Vasquez",
        headline: "Bilingual ELA & ESL Lead",
        avatarUrl: "https://randomuser.me/api/portraits/women/65.jpg",
        verificationTier: "premier",
        overallRating: 4.95,
        reviewCount: 31,
        gradeLevels: ["k5", "6_8", "9_12"],
        areasOfNeed: ["instruction_curriculum", "school_improvement"],
        engagementTypes: ["consulting", "permanent"],
        coverageRegions: ["region_2", "region_3"],
        startingRate: 82,
        availabilityStatus: "open",
        hasVideoIntro: true,
        badges: ["Background Checked", "State Licensed TX"],
    },
    {
        id: "e_4",
        name: "James Okonkwo",
        headline: "District Data Analyst & Assessment Lead",
        avatarUrl: "https://randomuser.me/api/portraits/men/75.jpg",
        verificationTier: "verified",
        overallRating: 4.6,
        reviewCount: 12,
        gradeLevels: ["6_8", "9_12", "all"],
        areasOfNeed: ["data", "mgmt_planning"],
        engagementTypes: ["consulting"],
        coverageRegions: ["region_1"],
        startingRate: 95,
        availabilityStatus: "open",
        hasVideoIntro: false,
        badges: ["Background Checked"],
    },
    {
        id: "e_5",
        name: "Priya Sharma",
        headline: "STEM Coordinator & AP Chemistry",
        avatarUrl: "https://randomuser.me/api/portraits/women/17.jpg",
        verificationTier: "premier",
        overallRating: 4.88,
        reviewCount: 56,
        gradeLevels: ["9_12"],
        areasOfNeed: ["instruction_curriculum", "leadership"],
        engagementTypes: ["permanent", "substitute"],
        coverageRegions: ["region_3", "region_5"],
        startingRate: 92,
        availabilityStatus: "limited",
        hasVideoIntro: true,
        badges: ["Background Checked", "NBCT"],
    },
    {
        id: "e_6",
        name: "Robert Chen",
        headline: "Long-Term Substitute — Secondary Math",
        avatarUrl: "https://randomuser.me/api/portraits/men/22.jpg",
        verificationTier: "basic",
        overallRating: 4.2,
        reviewCount: 7,
        gradeLevels: ["6_8", "9_12"],
        areasOfNeed: ["instruction_curriculum"],
        engagementTypes: ["substitute"],
        coverageRegions: ["region_2"],
        startingRate: 55,
        availabilityStatus: "open",
        hasVideoIntro: false,
        badges: ["Background Checked"],
    },
    {
        id: "e_7",
        name: "Amanda Foster",
        headline: "School Psychologist (LSSP)",
        avatarUrl: "https://randomuser.me/api/portraits/women/28.jpg",
        verificationTier: "verified",
        overallRating: 4.75,
        reviewCount: 22,
        gradeLevels: ["k5", "6_8"],
        areasOfNeed: ["developmental_medical", "school_improvement"],
        engagementTypes: ["consulting", "permanent"],
        coverageRegions: ["region_4"],
        startingRate: 110,
        availabilityStatus: "open",
        hasVideoIntro: true,
        badges: ["Background Checked", "State Licensed TX"],
    },
    {
        id: "e_8",
        name: "Derek Williams",
        headline: "HR & Talent Operations Consultant",
        avatarUrl: "https://randomuser.me/api/portraits/men/45.jpg",
        verificationTier: "verified",
        overallRating: 4.5,
        reviewCount: 9,
        gradeLevels: ["all"],
        areasOfNeed: ["human_resources", "mgmt_planning"],
        engagementTypes: ["consulting"],
        coverageRegions: ["region_1", "region_2", "region_3"],
        startingRate: 120,
        availabilityStatus: "limited",
        hasVideoIntro: false,
        badges: ["Background Checked"],
    },
    {
        id: "e_9",
        name: "Maria Santos",
        headline: "CFO-Level School Business & Accounting",
        avatarUrl: "https://randomuser.me/api/portraits/women/50.jpg",
        verificationTier: "premier",
        overallRating: 4.82,
        reviewCount: 19,
        gradeLevels: ["all"],
        areasOfNeed: ["accounting", "mgmt_planning"],
        engagementTypes: ["consulting", "permanent"],
        coverageRegions: ["region_5"],
        startingRate: 135,
        availabilityStatus: "open",
        hasVideoIntro: false,
        badges: ["Background Checked"],
    },
    {
        id: "e_10",
        name: "Kevin O'Brien",
        headline: "Facilitator — Board & Strategic Sessions",
        avatarUrl: "https://randomuser.me/api/portraits/men/59.jpg",
        verificationTier: "verified",
        overallRating: 4.65,
        reviewCount: 14,
        gradeLevels: ["all"],
        areasOfNeed: ["meeting_facilitation", "strategic_planning"],
        engagementTypes: ["consulting"],
        coverageRegions: ["region_1", "region_4"],
        startingRate: 88,
        availabilityStatus: "open",
        hasVideoIntro: true,
        badges: ["Background Checked"],
    },
    {
        id: "e_11",
        name: "Taylor Brooks",
        headline: "LMS Admin & Systems Implementation",
        avatarUrl: "https://randomuser.me/api/portraits/women/63.jpg",
        verificationTier: "verified",
        overallRating: 4.55,
        reviewCount: 11,
        gradeLevels: ["6_8", "9_12"],
        areasOfNeed: ["systems_development", "data"],
        engagementTypes: ["consulting", "permanent"],
        coverageRegions: ["region_3"],
        startingRate: 98,
        availabilityStatus: "limited",
        hasVideoIntro: false,
        badges: ["Background Checked"],
    },
    {
        id: "e_12",
        name: "Hassan Rahman",
        headline: "Project Manager — Bond & Facilities Programs",
        avatarUrl: "https://randomuser.me/api/portraits/men/67.jpg",
        verificationTier: "premier",
        overallRating: 4.78,
        reviewCount: 27,
        gradeLevels: ["all"],
        areasOfNeed: ["project_implementation", "mgmt_planning"],
        engagementTypes: ["consulting"],
        coverageRegions: ["region_2", "region_5"],
        startingRate: 105,
        availabilityStatus: "open",
        hasVideoIntro: true,
        badges: ["Background Checked"],
    },
    {
        id: "e_13",
        name: "Jennifer Liu",
        headline: "Literacy Coach — K–5",
        avatarUrl: "https://randomuser.me/api/portraits/women/89.jpg",
        verificationTier: "verified",
        overallRating: 4.7,
        reviewCount: 35,
        gradeLevels: ["k5"],
        areasOfNeed: ["instruction_curriculum", "school_improvement"],
        engagementTypes: ["consulting", "substitute"],
        coverageRegions: ["region_1"],
        startingRate: 72,
        availabilityStatus: "open",
        hasVideoIntro: true,
        badges: ["Background Checked", "NBCT"],
    },
    {
        id: "e_14",
        name: "Andre Patterson",
        headline: "Athletic Director & PE Curriculum",
        avatarUrl: "https://randomuser.me/api/portraits/men/11.jpg",
        verificationTier: "basic",
        overallRating: 4.35,
        reviewCount: 6,
        gradeLevels: ["6_8", "9_12"],
        areasOfNeed: ["instruction_curriculum", "leadership"],
        engagementTypes: ["permanent", "substitute"],
        coverageRegions: ["region_4"],
        startingRate: 62,
        availabilityStatus: "limited",
        hasVideoIntro: false,
        badges: ["Background Checked"],
    },
    {
        id: "e_15",
        name: "Sofia Ramirez",
        headline: "Occupational Therapist — Schools",
        avatarUrl: "https://randomuser.me/api/portraits/women/33.jpg",
        verificationTier: "verified",
        overallRating: 4.8,
        reviewCount: 24,
        gradeLevels: ["k5", "6_8"],
        areasOfNeed: ["developmental_medical"],
        engagementTypes: ["consulting", "permanent"],
        coverageRegions: ["region_3", "region_4"],
        startingRate: 102,
        availabilityStatus: "open",
        hasVideoIntro: false,
        badges: ["Background Checked", "State Licensed TX"],
    },
    {
        id: "e_16",
        name: "Greg Mitchell",
        headline: "Principal Coach — Turnaround Support",
        avatarUrl: "https://randomuser.me/api/portraits/men/41.jpg",
        verificationTier: "premier",
        overallRating: 4.92,
        reviewCount: 48,
        gradeLevels: ["all"],
        areasOfNeed: ["leadership", "school_improvement"],
        engagementTypes: ["consulting"],
        coverageRegions: ["region_1", "region_2", "region_3", "region_4", "region_5"],
        startingRate: 145,
        availabilityStatus: "limited",
        hasVideoIntro: true,
        badges: ["Background Checked", "NBCT"],
    },
    {
        id: "e_17",
        name: "Nina Patel",
        headline: "MTSS & RtI Program Designer",
        avatarUrl: "https://randomuser.me/api/portraits/women/55.jpg",
        verificationTier: "verified",
        overallRating: 4.68,
        reviewCount: 17,
        gradeLevels: ["k5", "6_8"],
        areasOfNeed: ["school_improvement", "data"],
        engagementTypes: ["consulting"],
        coverageRegions: ["region_2"],
        startingRate: 90,
        availabilityStatus: "open",
        hasVideoIntro: true,
        badges: ["Background Checked"],
    },
    {
        id: "e_18",
        name: "Chris Nguyen",
        headline: "CTE & Work-Based Learning Lead",
        avatarUrl: "https://randomuser.me/api/portraits/men/52.jpg",
        verificationTier: "verified",
        overallRating: 4.58,
        reviewCount: 13,
        gradeLevels: ["9_12"],
        areasOfNeed: ["instruction_curriculum", "project_implementation"],
        engagementTypes: ["permanent", "consulting"],
        coverageRegions: ["region_5"],
        startingRate: 78,
        availabilityStatus: "open",
        hasVideoIntro: false,
        badges: ["Background Checked"],
    },
    {
        id: "e_19",
        name: "Rachel Kim",
        headline: "Fine Arts Director — Music & Theater",
        avatarUrl: "https://randomuser.me/api/portraits/women/70.jpg",
        verificationTier: "basic",
        overallRating: 4.4,
        reviewCount: 8,
        gradeLevels: ["k5", "6_8", "9_12"],
        areasOfNeed: ["instruction_curriculum"],
        engagementTypes: ["substitute", "consulting"],
        coverageRegions: ["region_1"],
        startingRate: 58,
        availabilityStatus: "closed",
        hasVideoIntro: false,
        badges: ["Background Checked"],
    },
    {
        id: "e_20",
        name: "Omar Haddad",
        headline: "ELL Coordinator & Family Engagement",
        avatarUrl: "https://randomuser.me/api/portraits/men/68.jpg",
        verificationTier: "verified",
        overallRating: 4.72,
        reviewCount: 21,
        gradeLevels: ["k5", "6_8"],
        areasOfNeed: ["instruction_curriculum", "school_improvement"],
        engagementTypes: ["consulting"],
        coverageRegions: ["region_3", "region_4"],
        startingRate: 80,
        availabilityStatus: "open",
        hasVideoIntro: true,
        badges: ["Background Checked"],
    },
    {
        id: "e_21",
        name: "Denise Washington",
        headline: "Chief Academic Officer (Interim)",
        avatarUrl: "https://randomuser.me/api/portraits/women/12.jpg",
        verificationTier: "premier",
        overallRating: 4.9,
        reviewCount: 39,
        gradeLevels: ["all"],
        areasOfNeed: ["leadership", "strategic_planning"],
        engagementTypes: ["consulting"],
        coverageRegions: ["region_1", "region_2"],
        startingRate: 175,
        availabilityStatus: "limited",
        hasVideoIntro: true,
        badges: ["Background Checked", "State Licensed TX"],
    },
    {
        id: "e_22",
        name: "Luis Morales",
        headline: "Custodial & Ops Efficiency Consultant",
        avatarUrl: "https://randomuser.me/api/portraits/men/85.jpg",
        verificationTier: "basic",
        overallRating: 4.25,
        reviewCount: 5,
        gradeLevels: ["all"],
        areasOfNeed: ["mgmt_planning", "accounting"],
        engagementTypes: ["consulting"],
        coverageRegions: ["region_4"],
        startingRate: 70,
        availabilityStatus: "open",
        hasVideoIntro: false,
        badges: ["Background Checked"],
    },
    {
        id: "e_23",
        name: "Yuki Tanaka",
        headline: "Computer Science & Cybersecurity Teacher",
        avatarUrl: "https://randomuser.me/api/portraits/women/90.jpg",
        verificationTier: "verified",
        overallRating: 4.66,
        reviewCount: 16,
        gradeLevels: ["9_12"],
        areasOfNeed: ["instruction_curriculum", "systems_development"],
        engagementTypes: ["substitute", "permanent"],
        coverageRegions: ["region_2", "region_3"],
        startingRate: 88,
        availabilityStatus: "open",
        hasVideoIntro: true,
        badges: ["Background Checked"],
    },
    {
        id: "e_24",
        name: "Frank Delgado",
        headline: "Grant Writer — Federal & State Programs",
        avatarUrl: "https://randomuser.me/api/portraits/men/36.jpg",
        verificationTier: "verified",
        overallRating: 4.6,
        reviewCount: 10,
        gradeLevels: ["all"],
        areasOfNeed: ["mgmt_planning", "strategic_planning"],
        engagementTypes: ["consulting"],
        coverageRegions: ["region_5"],
        startingRate: 95,
        availabilityStatus: "limited",
        hasVideoIntro: false,
        badges: ["Background Checked"],
    },
    {
        id: "e_25",
        name: "Monique Jefferson",
        headline: "Restorative Practices & Climate Coach",
        avatarUrl: "https://randomuser.me/api/portraits/women/42.jpg",
        verificationTier: "premier",
        overallRating: 4.85,
        reviewCount: 33,
        gradeLevels: ["6_8", "9_12"],
        areasOfNeed: ["school_improvement", "leadership"],
        engagementTypes: ["consulting"],
        coverageRegions: ["region_1", "region_3"],
        startingRate: 92,
        availabilityStatus: "open",
        hasVideoIntro: true,
        badges: ["Background Checked", "NBCT"],
    },
    {
        id: "e_26",
        name: "Sam Rivera",
        headline: "Paraprofessional Trainer & SpEd Aide Lead",
        avatarUrl: "https://randomuser.me/api/portraits/men/77.jpg",
        verificationTier: "basic",
        overallRating: 4.3,
        reviewCount: 4,
        gradeLevels: ["k5", "6_8"],
        areasOfNeed: ["developmental_medical", "instruction_curriculum"],
        engagementTypes: ["substitute"],
        coverageRegions: ["region_4"],
        startingRate: 42,
        availabilityStatus: "open",
        hasVideoIntro: false,
        badges: ["Background Checked"],
    },
    {
        id: "e_27",
        name: "Dr. Helen Cho",
        headline: "Research & Evaluation — ESSA Compliance",
        avatarUrl: "https://randomuser.me/api/portraits/women/76.jpg",
        verificationTier: "premier",
        overallRating: 4.91,
        reviewCount: 29,
        gradeLevels: ["all"],
        areasOfNeed: ["data", "strategic_planning"],
        engagementTypes: ["consulting"],
        coverageRegions: ["region_2", "region_5"],
        startingRate: 125,
        availabilityStatus: "limited",
        hasVideoIntro: false,
        badges: ["Background Checked"],
    },
    {
        id: "e_28",
        name: "Jordan Blake",
        headline: "Substitute Pool — Elementary Generalist",
        avatarUrl: "https://randomuser.me/api/portraits/men/91.jpg",
        verificationTier: "basic",
        overallRating: 4.15,
        reviewCount: 3,
        gradeLevels: ["k5"],
        areasOfNeed: ["instruction_curriculum"],
        engagementTypes: ["substitute"],
        coverageRegions: ["region_3"],
        startingRate: 38,
        availabilityStatus: "open",
        hasVideoIntro: false,
        badges: ["Background Checked"],
    },
];

export function getMockEducatorById(id: string): EducatorCardProps | undefined {
    return MOCK_EDUCATORS.find((e) => e.id === id);
}

/** Full profile view — derived from card + light variation for demo depth */
export type MockEducatorProfileView = {
    name: string;
    initials: string;
    headline: string;
    verificationTier: "basic" | "verified" | "premier";
    availabilityStatus: "open" | "limited" | "closed";
    avatarUrl: string;
    bio: string;
    yearsExperience: number;
    placements: number;
    avgRating: number;
    reviewCount: number;
    location: string;
    education: string;
    areas: string[];
    badges: string[];
    licenses: { type: string; issuer: string; status: "Verified" | "Pending"; expiry: string }[];
    experience: { role: string; district: string; years: string }[];
    videoIntro: boolean;
    availableDays: Record<string, { am: boolean; pm: boolean }>;
    primarySubjectLabel: string;
    gradeLevelsLabel: string;
    certCount: number;
};

function initialsFromName(name: string): string {
    const parts = name.replace(/^(Dr\.|Mr\.|Ms\.|Mrs\.)\s+/i, "").split(/\s+/);
    const a = parts[0]?.[0] ?? "";
    const b = parts[parts.length - 1]?.[0] ?? "";
    return (a + b).toUpperCase() || "EG";
}

function hashId(id: string): number {
    let h = 0;
    for (let i = 0; i < id.length; i++) h = (h * 31 + id.charCodeAt(i)) >>> 0;
    return h;
}

export function getMockEducatorProfileView(educatorId: string): MockEducatorProfileView | null {
    const e = getMockEducatorById(educatorId);
    if (!e) return null;

    const h = hashId(e.id);
    const yearsExperience = 4 + (h % 18);
    const placements = 5 + (h % 40);

    const locs = [
        "Houston, TX (Hybrid)",
        "Dallas, TX (On-site)",
        "Austin, TX (Remote)",
        "San Antonio, TX (Hybrid)",
        "Fort Worth, TX (On-site)",
        "El Paso, TX (Remote)",
    ];
    const location = locs[h % locs.length];

    const schools = ["Austin ISD", "Houston ISD", "Northside ISD", "Fort Worth ISD", "Region 4 ESC", "Charter Network"];
    const areaLabels = e.areasOfNeed.slice(0, 3).map((id) => {
        const found = [
            { id: "instruction_curriculum", label: "Instruction & Curriculum" },
            { id: "data", label: "Data" },
            { id: "leadership", label: "Leadership" },
            { id: "school_improvement", label: "School Improvement" },
            { id: "developmental_medical", label: "Developmental & Medical" },
            { id: "mgmt_planning", label: "Management Planning" },
            { id: "human_resources", label: "Human Resources" },
            { id: "accounting", label: "Accounting" },
            { id: "meeting_facilitation", label: "Meeting Facilitation" },
            { id: "systems_development", label: "Systems Development" },
            { id: "project_implementation", label: "Project / Implementation" },
            { id: "strategic_planning", label: "Strategic Planning" },
        ].find((x) => x.id === id);
        return found?.label ?? id;
    });

    const gradeLabelMap: Record<string, string> = {
        k5: "K–5",
        "6_8": "6–8",
        "9_12": "9–12",
        all: "All grades",
    };
    const gradeLevelsLabel =
        e.gradeLevels.includes("all") ? "All grades" : e.gradeLevels.map((g) => gradeLabelMap[g] ?? g).join(", ");

    const bio = `${e.headline}. ${yearsExperience}+ years supporting districts with clear outcomes, collaborative planning, and measurable student impact. Available for ${e.engagementTypes.join(", ").replace(/_/g, " ")} engagements across ${e.coverageRegions.length} coverage region(s).`;

    const licenses: MockEducatorProfileView["licenses"] = [
        { type: "Standard Teaching Certificate", issuer: "Texas TEA", status: "Verified", expiry: String(2025 + (h % 4)) },
    ];
    if (e.verificationTier !== "basic") {
        licenses.push({
            type: "Supplemental Endorsement",
            issuer: "Texas TEA",
            status: h % 5 === 0 ? "Pending" : "Verified",
            expiry: String(2026 + (h % 3)),
        });
    }

    const amOpen = e.availabilityStatus === "open";
    const pmOpen = e.availabilityStatus !== "closed";

    return {
        name: e.name,
        initials: initialsFromName(e.name),
        headline: e.headline,
        verificationTier: e.verificationTier,
        availabilityStatus: e.availabilityStatus,
        avatarUrl: e.avatarUrl ?? `https://randomuser.me/api/portraits/men/${10 + (h % 80)}.jpg`,
        bio,
        yearsExperience,
        placements,
        avgRating: e.overallRating,
        reviewCount: e.reviewCount,
        location,
        education: h % 2 === 0 ? "M.Ed, Educational Leadership" : "Ed.D, Curriculum & Instruction",
        areas: areaLabels.length ? areaLabels : ["K-12 Support"],
        badges: e.badges ?? ["Background Checked"],
        licenses,
        experience: [
            { role: e.headline.split("—")[0].trim(), district: schools[h % schools.length], years: `${2015 + (h % 5)}–Present` },
            { role: "Prior district role", district: schools[(h + 1) % schools.length], years: `${2008 + (h % 5)}–${2014 + (h % 3)}` },
        ],
        videoIntro: e.hasVideoIntro,
        availableDays: {
            M: { am: amOpen, pm: pmOpen },
            T: { am: amOpen, pm: pmOpen },
            W: { am: amOpen, pm: pmOpen },
            Th: { am: amOpen, pm: h % 3 !== 0 },
            F: { am: h % 4 !== 0, pm: false },
        },
        primarySubjectLabel: areaLabels[0] ?? "General",
        gradeLevelsLabel,
        certCount: e.badges?.length ?? 2,
    };
}

/** Recent placement rows for district dashboard */
export const MOCK_RECENT_PLACEMENTS: { name: string; id: string; role: string; location: string; date: string }[] = [
    { name: "Dr. Sarah Jenkins", id: "e_1", role: "SpEd Consultant", location: "Lincoln High", date: "Today" },
    { name: "Elena Vasquez", id: "e_3", role: "Bilingual ELA Lead", location: "Roosevelt MS", date: "Today" },
    { name: "James Okonkwo", id: "e_4", role: "Assessment & Data", location: "District Office", date: "Yesterday" },
    { name: "Priya Sharma", id: "e_5", role: "STEM Coordinator", location: "Westside HS", date: "Yesterday" },
    { name: "Amanda Foster", id: "e_7", role: "School Psychologist", location: "Maple Elementary", date: "Mon" },
    { name: "Greg Mitchell", id: "e_16", role: "Principal Coach", location: "Turnaround Cohort", date: "Mon" },
    { name: "Monique Jefferson", id: "e_25", role: "Climate & Culture", location: "District Wide", date: "Sun" },
    { name: "Marcus Cole, M.Ed", id: "e_2", role: "Behavioral & SpEd Consultant", location: "District Wide", date: "Last week" },
];
