import fs from 'node:fs';
import { execFileSync, spawnSync } from 'node:child_process';
import { checkStaging } from './guard.mjs';
process.loadEnvFile('.env.local');
const r = checkStaging(process.env);
const project = JSON.parse(fs.readFileSync('.vercel/project.json'));
if (project.projectId !== r.vercelProjectId || project.orgId !== r.vercelTeamId) throw Error('Refusing deploy: wrong Vercel project');
const status = execFileSync('git', ['status','--porcelain'], {encoding:'utf8'});
if (status.trim()) throw Error('Commit reviewed staging changes first so deployment revision is reproducible');
const sha = execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim();
const result = spawnSync('vercel', ['deploy','--prod','--yes','--scope','asala','--meta',`qaCommit=${sha}`],{stdio:'inherit'});
process.exit(result.status ?? 1);
